services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: rr-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - rr-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: rr-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: rr-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://rr-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - rr-net

  cassandra:
    image: cassandra:4.1
    container_name: rr-cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: rr-cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - rr-net

  mysql:
    image: mysql:8.0
    container_name: rr-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: etl_dw
      MYSQL_USER: etl_user
      MYSQL_PASSWORD: etl_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
    networks:
      - rr-net

  spark-master:
    image: bitnamilegacy/spark:3.5.1
    container_name: rr-spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
      SPARK_RPC_ENCRYPTION_ENABLED: "no"
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
      SPARK_SSL_ENABLED: "no"
    volumes:
      - ./jobs:/opt/project/jobs
      - ./data:/opt/project/data
      - ./checkpoints:/opt/project/checkpoints
    networks:
      - rr-net

  spark-worker:
    image: bitnamilegacy/spark:3.5.1
    container_name: rr-spark-worker
    depends_on:
      - spark-master
    ports:
      - "18081:8081"
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://rr-spark-master:7077
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
      SPARK_RPC_ENCRYPTION_ENABLED: "no"
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
      SPARK_SSL_ENABLED: "no"
    volumes:
      - ./jobs:/opt/project/jobs
      - ./data:/opt/project/data
      - ./checkpoints:/opt/project/checkpoints
    networks:
      - rr-net

  grafana:
    image: grafana/grafana:10.4.2
    container_name: rr-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - mysql
    networks:
      - rr-net
  airflow-init:
    image: apache/airflow:2.10.5-python3.11
    container_name: rr-airflow-init
    depends_on:
      - kafka
      - cassandra
      - mysql
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__WEBSERVER__SECRET_KEY: "local-dev-secret-key"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      _PIP_ADDITIONAL_REQUIREMENTS: "kafka-python==2.0.2 mysql-connector-python==8.4.0 cassandra-driver==3.29.2 google-cloud-storage==2.18.2"
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/gcp-key/gcs-reader-key.json
      GCP_BUCKET_NAME: realtime-recruitment-raw-tracking-thanhtri-21130578
      GCP_OBJECT_NAME: tracking.csv
      LOCAL_TRACKING_PATH: /opt/airflow/data/raw/tracking.csv
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./jobs:/opt/airflow/jobs
      - ./data:/opt/airflow/data
      - ./gcp-key:/opt/airflow/gcp-key:ro
    command: >
      bash -c "airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Thanh
      --lastname Tri
      --role Admin
      --email admin@example.com || true"
    networks:
      - rr-net

  airflow-webserver:
    image: apache/airflow:2.10.5-python3.11
    container_name: rr-airflow-webserver
    depends_on:
      - airflow-init
    ports:
      - "8090:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__WEBSERVER__SECRET_KEY: "local-dev-secret-key"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      _PIP_ADDITIONAL_REQUIREMENTS: "kafka-python==2.0.2 mysql-connector-python==8.4.0 cassandra-driver==3.29.2 google-cloud-storage==2.18.2"
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/gcp-key/gcs-reader-key.json
      GCP_BUCKET_NAME: realtime-recruitment-raw-tracking-thanhtri-21130578
      GCP_OBJECT_NAME: tracking.csv
      LOCAL_TRACKING_PATH: /opt/airflow/data/raw/tracking.csv
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./jobs:/opt/airflow/jobs
      - ./data:/opt/airflow/data
      - ./gcp-key:/opt/airflow/gcp-key:ro
    command: webserver
    networks:
      - rr-net

  airflow-scheduler:
    image: apache/airflow:2.10.5-python3.11
    container_name: rr-airflow-scheduler
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__WEBSERVER__SECRET_KEY: "local-dev-secret-key"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      _PIP_ADDITIONAL_REQUIREMENTS: "kafka-python==2.0.2 mysql-connector-python==8.4.0 cassandra-driver==3.29.2 google-cloud-storage==2.18.2"
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/gcp-key/gcs-reader-key.json
      GCP_BUCKET_NAME: realtime-recruitment-raw-tracking-thanhtri-21130578
      GCP_OBJECT_NAME: tracking.csv
      LOCAL_TRACKING_PATH: /opt/airflow/data/raw/tracking.csv
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./jobs:/opt/airflow/jobs
      - ./data:/opt/airflow/data
      - ./gcp-key:/opt/airflow/gcp-key:ro
    command: scheduler
    networks:
      - rr-net

volumes:
  cassandra_data:
  mysql_data:
  grafana_data:
  airflow_data:

networks:
  rr-net:
    driver: bridge